const BAD_REQUEST = 400;
const NOT_FOUND_CODE = 404;
const CREATED_CODE = 201;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST, NOT_FOUND_CODE, CREATED_CODE, INTERNAL_SERVER_ERROR,
};